#! /usr/bin/env python

#! encoding:utf-8

# Filename:Tkinter_Button_Test.py

from tkinter import *

from tkinter import messagebox
#注意python 3 和python 2 的区别：2:import tkMessageBox


root = Tk()

root.title("Button Test")

def callback():

    messagebox.showinfo("Python command","人生苦短、我用Python")
#messagebox的用法
#


"""

创建4个Button按钮、并设置width，height,relief,bg,bd,fg,state,bitmap,command,anchor

"""

#pack():以块的方式组织组件，如同用石块（组件）堆积金字塔（父组件）一样.
Button(root, text="外观装饰边界附近的标签", width=19,relief=GROOVE,bg="red").pack()

Button(root, text="设置按钮状态",width=21,state=DISABLED).pack()

Button(root, text="设置bitmap放到按钮左边位置", compound="left",bitmap="error").pack()

Button(root, text="设置command事件调用命令", fg="blue",bd=2,width=28,command=callback).pack()

Button(root, text ="设置高度宽度以及文字显示位置",anchor = 'sw',width = 30,height = 2).pack()

root.mainloop()
